on:
  schedule:
    - cron: "0 12 * * 1"
  push:
    path:
      .github/workflows/build-packages.yaml
      build_binaries.R
      packages.txt

name: Build packages

jobs:
  render:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-18.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}

    env:
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install remotes+devtools
        run: |
          install.packages('devtools')
        shell: Rscript {0}

      - name: Install drat.builder + other packages
        run: |
          remotes::install_github('PredictiveEcology/Require@development')
          remotes::install_github('richfitz/drat.builder')
        shell: Rscript {0}

      - name: Configure git
        run: |
          git config --global user.name "[drat bot]"
          git config --global user.email "actions@github.com"

      - name: Build source packages
        if: runner.os == 'Linux'
        run: |
          Rscript -e "drat.builder::build()"

      - name: Build binary packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gdal imagemagick@6 libgit2 udunits
          Rscript -e 'install.packages(c("sf", "rgdal"), configure.args = c("--with-proj-lib=/usr/local/lib/", "--with-proj-include=/usr/local/include/"))'
          Rscript build_binaries.R
          git commit -a -m 'add latest binary packages for macOS'
          git pull -s ours origin ${{ github.ref }}

      - name: Build binary packages (Windows)
        if: runner.os == 'Windows'
        run: |
          Rscript build_binaries.R
          git commit -a -m 'add latest binary packages for Windows'
          git pull -s ours origin ${{ github.ref }}

      - name: Push results
        run: |
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
